apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170264273
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170264273
    app.kubernetes.io/part-of: test-app-170264273
  name: java-quarkus-170264273
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170264273
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170264273
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170264273/java-quarkus-170264273@sha256:385c685f08516c73419382ba1b28736f60f4a38ba155ee30623e72149e011bcb
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
